---

- name: brave | apt key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
  become: yes

- name: brave | apt repo
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
  become: yes

- name: brave | install
  apt:
    name:
      - brave-browser
  become: yes
