---

- name: install basic packages
  apt:
    name: "{{ item }}"
  with_items:
    - curl
    - python3-pip
    - screen
    - tmux
    - vim
    - zsh
  become: yes

- name: oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: yes  # fails the second time

- name: atom | apt key
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
  become: yes

- name: atom | apt repo
  apt_repository:
    repo: deb https://packagecloud.io/AtomEditor/atom/any/ any main
  become: yes

- name: atom | install
  apt:
    name: atom
  become: yes

- name: atom | install prefs
  copy:
    src: config.cson
    dest: "{{ ansible_user_dir }}/.atom/"

- name: atom | install extensions
  shell: apm install {{ item }}
  with_items:
    - advanced-open-file
    - atom-beautify
    - autocomplete
    - autocomplete-clang
    - busy-signal
    - git-blame
    - git-time-machine
    - hyperclick
    - intentions
    - language-cmake
    - language-docker
    - language-openscad
    - linter
    - linter-flake8
    - linter-ui-default
    - markdown-preview-plus
    - revert-buffer
    - split-diff
    - vim-mode-plus
    - you-complete-me

- name: appearance packages
  apt:
    name: gnome-tweaks
  become: yes
