---

- set_fact:
    distro: bionic

- name: basics | common apt packages
  apt:
    name:
    - curl
    - htop
    - openssh-server
    - python3-pip
    - screen
    - tmux
    - tree
    - vim
    - zsh
  become: yes

- name: basics | install some core pip stuff
  pip:
    name:
      - virtualenv
      - docker-compose

- name: oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: yes  # fails the second time

- name: atom | apt key
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
  become: yes

- name: atom | apt repo
  apt_repository:
    repo: deb https://packagecloud.io/AtomEditor/atom/any/ any main
  become: yes

- name: atom | install
  apt:
    name: atom
  become: yes

- name: atom | install prefs
  copy:
    src: config.cson
    dest: "{{ ansible_user_dir }}/.atom/"

- name: atom | install extensions
  shell: apm install \
    advanced-open-file \
    atom-beautify \
    autocomplete \
    autocomplete-clang \
    busy-signal \
    git-blame \
    git-time-machine \
    hyperclick \
    intentions \
    language-cmake \
    language-docker \
    language-openscad \
    linter \
    linter-flake8 \
    linter-ui-default \
    markdown-preview-plus \
    revert-buffer \
    split-diff \
    vim-mode-plus \
    you-complete-me

- name: appearance packages
  apt:
    name:
    - gnome-tweaks
    - gnome-shell-extension-system-monitor
  become: yes

- name: docker | prereqs
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: yes

- name: docker | apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: docker | apt repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
  become: yes

- name: docker | install
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes

- name: docker | add me to group
  user:
    append: yes
    groups:
      - docker
    name: "{{ ansible_user }}"
  become: yes

- name: brave | apt key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
  become: yes

- name: brave | apt repo
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
  become: yes

- name: brave | install
  apt:
    name:
      - brave-browser
  become: yes


- name: ros
  include_tasks: ros.yml
