
- name: ros | install ws management prereqs
  pip:
    name: vcstool

- name: ros | install linters
  pip:
    name:
      - flake8
      - flake8-blind-except
      - flake8-builtins
      - flake8-class-newline
      - flake8-comprehensions
      - flake8-deprecated
      - flake8-docstrings
      - flake8-import-order
      - flake8-quotes
